version: "3.8"

services:
  livekit-mmla-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: livekit-mmla-api:latest
    container_name: livekit-mmla-api-container
    ports:
      - "8081:8081"
    env_file:
      - ../.env
