redis:
    address: localhost:6379
    username: ""
    password: ""
    db: 0
    use_tls: false
    sentinel_master_name: ""
    sentinel_username: ""
    sentinel_password: ""
    sentinel_addresses: []
    cluster_addresses: []
    max_redirects: null
api_key: APIEHGtzk9DKyjY
api_secret: 8dINIFYmXdB4lJf9LFlrV5XsuMkmjWH2QT32iYLUw4b
ws_url: ws://localhost:7880
