redis:
    address: localhost:6379
    username: ""
    password: ""
    db: 0
    use_tls: false
    sentinel_master_name: ""
    sentinel_username: ""
    sentinel_password: ""
    sentinel_addresses: []
    cluster_addresses: []
    max_redirects: null
api_key: APIfJENwGJaE6DD
api_secret: cmPbeYxmovNQ4zb7HnABS1eKF4GSm0PX9MTtci0fFi7A
ws_url: ws://localhost:7880
insecure: true
