port: 7880
rtc:
    udp_port: 7882
    tcp_port: 7881
    use_external_ip: false
    enable_loopback_candidate: false
keys:
    APIfJENwGJaE6DD: cmPbeYxmovNQ4zb7HnABS1eKF4GSm0PX9MTtci0fFi7A
logging:
    json: false
    level: info
redis:
    address: 172.18.0.2:6379
